### ISSUE TITLE
URLError?

### ISSUE THREAD

**Issue by codeinthehole** [roadsideseb/virtual-less#2]
Just tried to pip install this locally and got a URLError:

I'm short of time today and so haven't looked into the details sorry.

```
Running setup.py install for virtual-less
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/dwinterbottom/.virtualenvs/meridian/build/virtual-less/setup.py", line 12, in <module>
        less_zip = urlopen("https://github.com/cloudhead/less.js/archive/v1.3.3.zip")
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
        response = meth(req, response)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
        'http', request, response, code, msg, hdrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 432, in error
        result = self._call_chain(*args)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
        result = func(*args)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 619, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
        response = self._open(req, data)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
        '_open', req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
        result = func(*args)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1207, in https_open
        return self.do_open(httplib.HTTPSConnection, req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno 8] _ssl.c:503: EOF occurred in violation of protocol>
    Complete output from command /Users/dwinterbottom/.virtualenvs/meridian/bin/python -c "import setuptools;__file__='/Users/dwinterbottom/.virtualenvs/meridian/build/virtual-less/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/36/rgzf6zjs4r57rv935fsv2g5h0009v9/T/pip-DSaCWb-record/install-record.txt --single-version-externally-managed --install-headers /Users/dwinterbottom/.virtualenvs/meridian/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/dwinterbottom/.virtualenvs/meridian/build/virtual-less/setup.py", line 12, in <module>

    less_zip = urlopen("https://github.com/cloudhead/less.js/archive/v1.3.3.zip")

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen

    return _opener.open(url, data, timeout)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open

    response = meth(req, response)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response

    'http', request, response, code, msg, hdrs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 432, in error

    result = self._call_chain(*args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain

    result = func(*args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 619, in http_error_302

    return self.parent.open(new, timeout=req.timeout)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open

    response = self._open(req, data)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open

    '_open', req)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain

    result = func(*args)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1207, in https_open

    return self.do_open(httplib.HTTPSConnection, req)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open

    raise URLError(err)

urllib2.URLError: <urlopen error [Errno 8] _ssl.c:503: EOF occurred in violation of protocol>

----------------------------------------
Command /Users/dwinterbottom/.virtualenvs/meridian/bin/python -c "import setuptools;__file__='/Users/dwinterbottom/.virtualenvs/meridian/build/virtual-less/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/36/rgzf6zjs4r57rv935fsv2g5h0009v9/T/pip-DSaCWb-record/install-record.txt --single-version-externally-managed --install-headers /Users/dwinterbottom/.virtualenvs/meridian/include/site/python2.7 failed with error code 1 in /Users/dwinterbottom/.virtualenvs/meridian/build/virtual-less
Storing complete log in /Users/dwinterbottom/.pip/pip.log
```

**Comment by roadsideseb** [comment]
Hmm, good question. I just tried installing it in a fresh virtualenv and it worked fine. The problem you where having seems to have occurred while downloading the source files for less from github. Could have been a temporary poblem with the download. Would you mind giving it another try (when you have time) to see if the problem persists?

**Comment by mbelarbi** [comment]
I am getting the exact same issue. Fresh virtualenv, and clean `pip install virtual-less`.

**Comment by roadsideseb** [comment]
I just ran a `wget https://github.com/cloudhead/less.js/archive/v1.3.3.zip` and get a 500 error there as well. Seems that it's an issue with github again. The file is not available due to [an attack disrupting the service](https://status.github.com/). I'd recommend checking it again in a few minutes.

**Comment by roadsideseb** [comment]
I just tried it in a fresh virtualenv and since github is working the installation worked as well. I'm closing this issue.
